"""
convert_profile_photo.py — Resize a profile photo and convert to a C array
for the Ori firmware profile photo placeholder.

Accepts: JPG, PNG (including transparent), WebP.
Place your photo here (one file), then run:
    python convert_profile_photo.py

Output: firmware/src/assets/profile_placeholder.c
Target size: 228 × 228 px (displayed circular-cropped by LVGL on device).
The firmware decodes this JPEG from flash into PSRAM once at boot.

Dependencies:
    pip install pillow
"""

import os
import sys
from PIL import Image

# ── Config ────────────────────────────────────────────────────────────────────
TARGET_W   = 228
TARGET_H   = 228
QUALITY    = 80          # JPEG quality (75-85 recommended; ≤40 KB hard cap)
C_SYMBOL   = "profile_placeholder_jpg"
# ─────────────────────────────────────────────────────────────────────────────

HERE         = os.path.dirname(os.path.abspath(__file__))
FIRMWARE_DIR = os.path.abspath(os.path.join(HERE, "..", ".."))
OUTPUT_DIR   = os.path.join(FIRMWARE_DIR, "src", "assets")
OUTPUT_FILE  = os.path.join(OUTPUT_DIR, "profile_placeholder.c")
EXTS         = (".jpg", ".jpeg", ".png", ".webp")


def find_source() -> str:
    images = [f for f in os.listdir(HERE) if os.path.splitext(f)[1].lower() in EXTS]
    if not images:
        print("ERROR: No JPG/PNG/WebP file found in firmware/img/profile_photo/")
        print("Place your profile photo here and re-run.")
        sys.exit(1)
    if len(images) > 1:
        print(f"Found {len(images)} images — using first: {sorted(images)[0]}")
    return os.path.join(HERE, sorted(images)[0])


def resize(src: str) -> bytes:
    img = Image.open(src)
    # Composite PNG/WebP transparency against white before converting to RGB.
    # (convert("RGB") alone composites against black, which looks wrong for photos.)
    if img.mode in ("RGBA", "LA", "P"):
        bg = Image.new("RGB", img.size, (255, 255, 255))
        if img.mode == "P":
            img = img.convert("RGBA")
        bg.paste(img, mask=img.split()[-1] if img.mode in ("RGBA", "LA") else None)
        img = bg
    else:
        img = img.convert("RGB")
    orig_w, orig_h = img.size
    # Square crop from centre before resizing.
    if orig_w != orig_h:
        side = min(orig_w, orig_h)
        x0 = (orig_w - side) // 2
        y0 = (orig_h - side) // 2
        img = img.crop((x0, y0, x0 + side, y0 + side))
    img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)

    import io
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=QUALITY, optimize=True)
    return buf.getvalue()


def to_c_array(data: bytes) -> str:
    lines = [
        f"// Profile photo placeholder — {TARGET_W}×{TARGET_H} JPEG ({len(data)} bytes)\n",
        f"// Generated by firmware/img/profile_photo/convert_profile_photo.py\n",
        f"// DO NOT EDIT — re-run the script to regenerate.\n\n",
        f"const unsigned char {C_SYMBOL}[] = {{\n",
    ]
    for i, b in enumerate(data):
        if i % 16 == 0:
            lines.append("    ")
        lines.append(f"0x{b:02X},")
        lines.append("\n" if i % 16 == 15 else " ")
    lines.append(f"\n}};\n")
    lines.append(f"const unsigned int {C_SYMBOL}_len = {len(data)};\n")
    return "".join(lines)


def main():
    src = find_source()
    print(f"Source  : {os.path.basename(src)}")
    print(f"Target  : {TARGET_W}×{TARGET_H} px (square crop), JPEG quality {QUALITY}")

    jpeg_bytes = resize(src)
    print(f"Size    : {len(jpeg_bytes):,} bytes", end="")
    if len(jpeg_bytes) > 40 * 1024:
        print(f"  ← WARNING: exceeds 40 KB hard cap! Lower QUALITY in script.")
    else:
        print()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(to_c_array(jpeg_bytes))

    print(f"Output  : {os.path.relpath(OUTPUT_FILE)}")
    print("Done. Rebuild firmware to include the new placeholder.")


if __name__ == "__main__":
    main()
