#pragma once

#include <lvgl.h>

// Color-emoji support for UI text.
//
// A curated set of Microsoft Fluent Emoji (MIT) 3D glyphs is baked into flash as
// RGB565+A8 images (src/assets/emoji_assets.c, generated by
// img/emoji/convert_emoji.py). This wraps them in an LVGL imgfont whose path_cb
// maps a Unicode codepoint -> compiled-in image. Installed as the .fallback of
// the UI text fonts (theme.cpp), so emoji in ANCS notification text render
// inline instead of being stripped by ui::sanitize_text().

namespace emoji_font {

// Shared color-emoji imgfont, created on first call. Returns nullptr if the
// emoji set is empty or LVGL couldn't create the font. Intended to be set as
// the .fallback on the text fonts.
const lv_font_t* get();

}  // namespace emoji_font
