#include "assets/ancs_icons.h"

#include <string.h>

// Compiled-in raster icon assets (60×60 RGB565, generated by LVGL image converter).
// Add an extern here and a row in k_images below for each new icon file added to
// firmware/src/assets/.
extern "C" {
    extern const lv_image_dsc_t gmail;
    extern const lv_image_dsc_t messenger;
    extern const lv_image_dsc_t instagram;
    extern const lv_image_dsc_t facebook;
    extern const lv_image_dsc_t whatsapp;
    extern const lv_image_dsc_t slack;
    extern const lv_image_dsc_t twitter;
    extern const lv_image_dsc_t teams;
    extern const lv_image_dsc_t sms;
    extern const lv_image_dsc_t phone;
    extern const lv_image_dsc_t discord;
    extern const lv_image_dsc_t telegram;
    extern const lv_image_dsc_t youtube;
    extern const lv_image_dsc_t tiktok;
    extern const lv_image_dsc_t spotify;
    extern const lv_image_dsc_t wechat;
    extern const lv_image_dsc_t line;
    extern const lv_image_dsc_t zoom;
    extern const lv_image_dsc_t outlook;
    extern const lv_image_dsc_t snapchat;
    extern const lv_image_dsc_t google_meet;
    extern const lv_image_dsc_t facetime;
    extern const lv_image_dsc_t linkedin;
    extern const lv_image_dsc_t reddit;
    extern const lv_image_dsc_t threads;
    extern const lv_image_dsc_t twitch;
    extern const lv_image_dsc_t uber;
    extern const lv_image_dsc_t apple_music;
    extern const lv_image_dsc_t amazon;
}

namespace ancs_icons {

namespace {

struct Entry { const char* token; uint32_t rgb; };

// Brand colours per app token. Approximate — will be refined in M8.
// Entries cover every token in mock_data.cpp and ancs_client.cpp's bundle map.
static const Entry k_table[] = {
    { "gmail",       0xEA4335 },
    { "messenger",   0x006AFF },
    { "instagram",   0xE1306C },
    { "facebook",    0x1877F2 },
    { "whatsapp",    0x25D366 },
    { "slack",       0x4A154B },
    { "twitter",     0x1DA1F2 },
    { "teams",       0x464EB8 },
    { "sms",         0x3DC95E },
    { "phone",       0x34C759 },
    { "discord",     0x5865F2 },
    { "telegram",    0x26A5E4 },
    { "youtube",     0xFF0000 },
    { "tiktok",      0xFF0050 },
    { "spotify",     0x1DB954 },
    { "wechat",      0x07C160 },
    { "line",        0x00B900 },
    { "zoom",        0x2D8CFF },
    { "outlook",     0x0078D4 },
    { "snapchat",    0xFFFC00 },
    { "google_meet", 0x00897B },
    { "facetime",    0x59C974 },
    { "linkedin",    0x0A66C2 },
    { "reddit",      0xFF4500 },
    { "threads",     0x000000 },
    { "twitch",      0x9146FF },
    { "uber",        0x000000 },
    { "apple_music", 0xFC3C44 },
    { "amazon",      0xFF9900 },
};

} // namespace

uint32_t color(const char* token) {
    if (!token) return 0x555555;
    for (const auto& e : k_table) {
        if (strcmp(e.token, token) == 0) return e.rgb;
    }
    return 0x555555;
}

namespace {
struct ImageEntry { const char* token; const lv_image_dsc_t* dsc; };
static const ImageEntry k_images[] = {
    { "gmail",       &gmail       },
    { "messenger",   &messenger   },
    { "instagram",   &instagram   },
    { "facebook",    &facebook    },
    { "whatsapp",    &whatsapp    },
    { "slack",       &slack       },
    { "twitter",     &twitter     },
    { "teams",       &teams       },
    { "sms",         &sms         },
    { "phone",       &phone       },
    { "discord",     &discord     },
    { "telegram",    &telegram    },
    { "youtube",     &youtube     },
    { "tiktok",      &tiktok      },
    { "spotify",     &spotify     },
    { "wechat",      &wechat      },
    { "line",        &line        },
    { "zoom",        &zoom        },
    { "outlook",     &outlook     },
    { "snapchat",    &snapchat    },
    { "google_meet", &google_meet },
    { "facetime",    &facetime    },
    { "linkedin",    &linkedin    },
    { "reddit",      &reddit      },
    { "threads",     &threads     },
    { "twitch",      &twitch      },
    { "uber",        &uber        },
    { "apple_music", &apple_music },
    { "amazon",      &amazon      },
};
} // namespace

const lv_image_dsc_t* image(const char* token) {
    if (!token) return nullptr;
    for (const auto& e : k_images) {
        if (strcmp(e.token, token) == 0) return e.dsc;
    }
    return nullptr;
}

} // namespace ancs_icons
