#include "assets/ancs_icons.h"

#include <string.h>

// Compiled-in raster icon assets (60×60 RGB565, generated by LVGL image converter).
// Add an extern here and a row in k_images below for each new icon file added to
// firmware/src/assets/.
extern "C" {
    extern const lv_image_dsc_t gmail;
    extern const lv_image_dsc_t messenger;
    extern const lv_image_dsc_t instagram;
    extern const lv_image_dsc_t facebook;
    extern const lv_image_dsc_t whatsapp;
    extern const lv_image_dsc_t slack;
    extern const lv_image_dsc_t twitter;
    extern const lv_image_dsc_t teams;
    extern const lv_image_dsc_t sms;
    extern const lv_image_dsc_t phone;
}

namespace ancs_icons {

namespace {

struct Entry { const char* token; uint32_t rgb; };

// Brand colours per app token. Approximate — will be refined in M8.
// Entries cover every token in mock_data.cpp and ancs_client.cpp's bundle map.
static const Entry k_table[] = {
    { "gmail",     0xEA4335 },
    { "messenger", 0x006AFF },
    { "instagram", 0xE1306C },
    { "facebook",  0x1877F2 },
    { "whatsapp",  0x25D366 },
    { "slack",     0x4A154B },
    { "twitter",   0x1DA1F2 },
    { "teams",     0x464EB8 },
    { "sms",       0x3DC95E },
    { "phone",     0x34C759 },
};

} // namespace

uint32_t color(const char* token) {
    if (!token) return 0x555555;
    for (const auto& e : k_table) {
        if (strcmp(e.token, token) == 0) return e.rgb;
    }
    return 0x555555;
}

namespace {
struct ImageEntry { const char* token; const lv_image_dsc_t* dsc; };
static const ImageEntry k_images[] = {
    { "gmail",     &gmail     },
    { "messenger", &messenger },
    { "instagram", &instagram },
    { "facebook",  &facebook  },
    { "whatsapp",  &whatsapp  },
    { "slack",     &slack     },
    { "twitter",   &twitter   },
    { "teams",     &teams     },
    { "sms",       &sms       },
    { "phone",     &phone     },
};
} // namespace

const lv_image_dsc_t* image(const char* token) {
    if (!token) return nullptr;
    for (const auto& e : k_images) {
        if (strcmp(e.token, token) == 0) return e.dsc;
    }
    return nullptr;
}

} // namespace ancs_icons
