"""
convert_pto_photo.py — Resize a PTO destination photo and convert to a C array
for the Ori firmware PTO placeholder.

Place your JPG here (one file), then run:
    python convert_pto_photo.py

Output: firmware/src/assets/pto_placeholder.c
Target size: 528 × 396 px (left panel dimensions — no scaling needed on device).
The firmware decodes this JPEG from flash into PSRAM once at boot.

Dependencies:
    pip install pillow
"""

import os
import sys
from PIL import Image

# ── Config ────────────────────────────────────────────────────────────────────
TARGET_W   = 528
TARGET_H   = 396
QUALITY    = 75          # JPEG quality (70-85 recommended; ≤64 KB hard cap)
C_SYMBOL   = "pto_placeholder_jpg"
# ─────────────────────────────────────────────────────────────────────────────

HERE         = os.path.dirname(os.path.abspath(__file__))
FIRMWARE_DIR = os.path.abspath(os.path.join(HERE, "..", ".."))
OUTPUT_DIR   = os.path.join(FIRMWARE_DIR, "src", "assets")
OUTPUT_FILE  = os.path.join(OUTPUT_DIR, "pto_placeholder.c")
EXTS         = (".jpg", ".jpeg", ".png", ".webp")


def find_source() -> str:
    images = [f for f in os.listdir(HERE) if os.path.splitext(f)[1].lower() in EXTS]
    if not images:
        print("ERROR: No JPG/PNG/WebP file found in firmware/img/pto_photo/")
        print("Place your destination photo here and re-run.")
        sys.exit(1)
    if len(images) > 1:
        print(f"Found {len(images)} images — using first: {sorted(images, key=str.lower)[0]}")
    return os.path.join(HERE, sorted(images, key=str.lower)[0])


def resize(src: str) -> bytes:
    img = Image.open(src).convert("RGB")
    orig_w, orig_h = img.size
    # Crop to target aspect ratio before resizing to avoid distortion.
    target_ratio = TARGET_W / TARGET_H
    orig_ratio   = orig_w  / orig_h
    if orig_ratio > target_ratio:
        # Too wide — crop sides.
        new_w = int(orig_h * target_ratio)
        x0 = (orig_w - new_w) // 2
        img = img.crop((x0, 0, x0 + new_w, orig_h))
    elif orig_ratio < target_ratio:
        # Too tall — crop top/bottom.
        new_h = int(orig_w / target_ratio)
        y0 = (orig_h - new_h) // 2
        img = img.crop((0, y0, orig_w, y0 + new_h))
    img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)

    import io
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=QUALITY, optimize=True)
    return buf.getvalue()


def to_c_array(data: bytes) -> str:
    lines = [
        f"// PTO placeholder image — {TARGET_W}×{TARGET_H} JPEG ({len(data)} bytes)\n",
        f"// Generated by firmware/img/pto_photo/convert_pto_photo.py\n",
        f"// DO NOT EDIT — re-run the script to regenerate.\n\n",
        f"const unsigned char {C_SYMBOL}[] = {{\n",
    ]
    for i, b in enumerate(data):
        if i % 16 == 0:
            lines.append("    ")
        lines.append(f"0x{b:02X},")
        lines.append("\n" if i % 16 == 15 else " ")
    lines.append(f"\n}};\n")
    lines.append(f"const unsigned int {C_SYMBOL}_len = {len(data)};\n")
    return "".join(lines)


def main():
    src = find_source()
    print(f"Source  : {os.path.basename(src)}")
    print(f"Target  : {TARGET_W}×{TARGET_H} px, JPEG quality {QUALITY}")

    jpeg_bytes = resize(src)
    print(f"Size    : {len(jpeg_bytes):,} bytes", end="")
    if len(jpeg_bytes) > 64 * 1024:
        print(f"  ← WARNING: exceeds 64 KB hard cap! Lower QUALITY in script.")
    else:
        print()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(to_c_array(jpeg_bytes))

    print(f"Output  : {os.path.relpath(OUTPUT_FILE)}")
    print("Done. Rebuild firmware to include the new placeholder.")


if __name__ == "__main__":
    main()
